/* ==========================================================
   ILS SHOP — Catalogue Produits
   Données de démonstration — à compléter/valider
   ========================================================== */

const ILS_PRODUCTS = [

  /* ────────────────────────────────
     LABORATORY — MEMMERT
     ──────────────────────────────── */
  {
    id: 'memmert-uf55',
    brand: 'Memmert',
    brandSlug: 'memmert',
    category: 'laboratory',
    subcategory: 'ovens',
    name: 'UF55 Universal Oven',
    nameEn: 'UF55 Universal Oven',
    nameFr: 'Étuve universelle UF55',
    ref: 'UF55',
    specs: ['30–300°C', '53 L', 'Forced air'],
    specsFr: ['30–300°C', '53 L', 'Air forcé'],
    description: 'Drying, sterilization, aging tests with excellent temperature uniformity.',
    descriptionFr: 'Séchage, stérilisation, tests de vieillissement avec excellente uniformité de température.',
    pdf: null,
    image: '/assets/images/products/memmert/csm_UF55-universal-oven-medical-device-open_996a36519f.webp'
  },
  {
    id: 'memmert-uf110',
    brand: 'Memmert',
    brandSlug: 'memmert',
    category: 'laboratory',
    subcategory: 'ovens',
    name: 'UF110 Universal Oven',
    nameEn: 'UF110 Universal Oven',
    nameFr: 'Étuve universelle UF110',
    ref: 'UF110',
    specs: ['30–300°C', '108 L', 'Forced air'],
    specsFr: ['30–300°C', '108 L', 'Air forcé'],
    description: 'High-capacity universal oven for demanding laboratory environments.',
    descriptionFr: 'Étuve universelle haute capacité pour laboratoires exigeants.',
    pdf: null,
    image: '/assets/images/products/memmert/csm_UF110-universal-oven-medical-device-open_2e1367746f.webp'
  },
  {
    id: 'memmert-in55',
    brand: 'Memmert',
    brandSlug: 'memmert',
    category: 'laboratory',
    subcategory: 'incubators',
    name: 'IN55 Incubator',
    nameEn: 'IN55 Incubator',
    nameFr: 'Incubateur IN55',
    ref: 'IN55',
    specs: ['0–70°C', '53 L', '±0.1°C'],
    specsFr: ['0–70°C', '53 L', '±0.1°C'],
    description: 'Cell culture, microbiology and sample incubation with precise thermal uniformity.',
    descriptionFr: 'Culture cellulaire, microbiologie et incubation d\'échantillons avec uniformité thermique précise.',
    pdf: null,
    image: '/assets/images/products/memmert/csm_IN55-incubator-open_4a3fbb50e7.webp'
  },
  {
    id: 'memmert-wb14',
    brand: 'Memmert',
    brandSlug: 'memmert',
    category: 'laboratory',
    subcategory: 'water-baths',
    name: 'WB14 Water Bath',
    nameEn: 'WB14 Water Bath',
    nameFr: 'Bain-marie WB14',
    ref: 'WB14',
    specs: ['30–95°C', '14 L', 'Stainless steel'],
    specsFr: ['30–95°C', '14 L', 'Inox'],
    description: 'Precise water bath for sample conditioning, enzymatic reactions and heating.',
    descriptionFr: 'Bain-marie de précision pour conditionnement d\'échantillons, réactions enzymatiques et chauffage.',
    pdf: null,
    image: '/assets/images/products/memmert/csm_wtb-15-water-bath-cover-open_15162d3542.webp'
  },
  {
    id: 'memmert-sb14',
    brand: 'Memmert',
    brandSlug: 'memmert',
    category: 'laboratory',
    subcategory: 'water-baths',
    name: 'SB14 Shaking Water Bath',
    nameEn: 'SB14 Shaking Water Bath',
    nameFr: 'Bain agitateur SB14',
    ref: 'SB14',
    specs: ['30–95°C', '14 L', '30–200 rpm'],
    specsFr: ['30–95°C', '14 L', '30–200 tr/min'],
    description: 'Shaking water bath combining precise temperature control with programmable orbital agitation.',
    descriptionFr: 'Bain agitateur combinant un contrôle précis de la température avec une agitation orbitale programmable.',
    pdf: null,
    image: '/assets/images/products/memmert/csm_wtb-24-water-bath-cover-open_05f3613c6d.webp'
  },
  {
    id: 'memmert-ich110',
    brand: 'Memmert',
    brandSlug: 'memmert',
    category: 'laboratory',
    subcategory: 'incubators',
    name: 'ICH110 Climatic Chamber',
    nameEn: 'ICH110 Climatic Chamber',
    nameFr: 'Chambre climatique ICH110',
    ref: 'ICH110',
    specs: ['10–70°C', '10–90% RH', '108 L'],
    specsFr: ['10–70°C', '10–90% HR', '108 L'],
    description: 'ICH-compliant climatic chamber for stability studies, long-term drug testing.',
    descriptionFr: 'Chambre climatique conforme ICH pour les études de stabilité et les tests de médicaments long terme.',
    pdf: null,
    image: '/assets/images/products/memmert/csm_ICH110-climate-chamber-open_b9a9717865.webp'
  },
  {
    id: 'memmert-ipp110',
    brand: 'Memmert',
    brandSlug: 'memmert',
    category: 'laboratory',
    subcategory: 'incubators',
    name: 'IPP110 Peltier Incubator',
    nameEn: 'IPP110 Peltier Incubator',
    nameFr: 'Incubateur Peltier IPP110',
    ref: 'IPP110',
    specs: ['0–60°C', '108 L', 'Cooling & heating'],
    specsFr: ['0–60°C', '108 L', 'Refroidissement & chauffage'],
    description: 'Peltier-cooled incubator for microorganisms, insects and enzyme reactions needing cooling.',
    descriptionFr: 'Incubateur refroidi par Peltier pour microorganismes, insectes et réactions enzymatiques nécessitant un refroidissement.',
    pdf: null,
    image: '/assets/images/products/memmert/csm_IPP110pluscooled-incubator-closed_0b34ab8e03.webp'
  },
  {
    id: 'memmert-uf260',
    brand: 'Memmert',
    brandSlug: 'memmert',
    category: 'laboratory',
    subcategory: 'ovens',
    name: 'UF260 Universal Oven',
    nameEn: 'UF260 Universal Oven',
    nameFr: 'Étuve universelle UF260',
    ref: 'UF260',
    specs: ['30–300°C', '256 L', 'Forced air'],
    specsFr: ['30–300°C', '256 L', 'Air forcé'],
    description: 'Large-capacity universal oven for industrial-scale drying and high-throughput testing.',
    descriptionFr: 'Grande étuve universelle pour le séchage industriel et les tests à haut débit.',
    pdf: null,
    image: '/assets/images/products/memmert/csm_UF260-universal-oven-medical-device-open_f8cb70b9a8.webp'
  },

  /* ────────────────────────────────
     LABORATORY — AMETEK BROOKFIELD
     ──────────────────────────────── */
  {
    id: 'brookfield-dv2t',
    brand: 'Brookfield',
    brandSlug: 'brookfield',
    category: 'laboratory',
    subcategory: 'viscometers',
    name: 'DV2T Viscometer',
    nameEn: 'DV2T Viscometer',
    nameFr: 'Viscosimètre DV2T',
    ref: 'DV2T',
    specs: ['1–40M mPa·s', '±1% accuracy', 'Touchscreen'],
    specsFr: ['1–40M mPa·s', '±1% précision', 'Écran tactile'],
    description: 'Advanced digital viscometer with touchscreen interface and data logging.',
    descriptionFr: 'Viscosimètre numérique avancé avec interface tactile et enregistrement de données.',
    pdf: null,
    image:'/assets/images/products/brookfield/dv2plus-front.png'
    
  },
  {
    id: 'brookfield-dve',
    brand: 'Brookfield',
    brandSlug: 'brookfield',
    category: 'laboratory',
    subcategory: 'viscometers',
    name: 'DV-E Viscometer',
    nameEn: 'DV-E Viscometer',
    nameFr: 'Viscosimètre DV-E',
    ref: 'DV-E',
    specs: ['15–6M mPa·s', '±1% accuracy', 'Entry level'],
    specsFr: ['15–6M mPa·s', '±1% précision', 'Entrée de gamme'],
    description: 'Entry-level digital viscometer, ideal for routine quality control.',
    descriptionFr: 'Viscosimètre numérique entrée de gamme, idéal pour le contrôle qualité de routine.',
    pdf: null,
    image: '/assets/images/products/brookfield/dvplus-viscometerproduct-page.png'
  },
  {
    id: 'brookfield-rst-cps',
    brand: 'Brookfield',
    brandSlug: 'brookfield',
    category: 'laboratory',
    subcategory: 'viscometers',
    name: 'RST-CPS Rheometer',
    nameEn: 'RST-CPS Rheometer',
    nameFr: 'Rhéomètre RST-CPS',
    ref: 'RST-CPS',
    specs: ['Controlled stress', 'Cone/Plate', 'Full rheology'],
    specsFr: ['Contrainte contrôlée', 'Cône/Plan', 'Rhéologie complète'],
    description: 'Complete rheological characterization with controlled stress and strain.',
    descriptionFr: 'Caractérisation rhéologique complète avec contrainte et déformation contrôlées.',
    pdf: null,
    image: '/assets/images/products/brookfield/rsx-cp.png'
  },

  /* ────────────────────────────────
     LABORATORY — PRECISA
     ──────────────────────────────── */
  {
    id: 'precisa-180a',
    brand: 'Precisa',
    brandSlug: 'precisa',
    category: 'laboratory',
    subcategory: 'balances',
    name: '180A SCS Analytical Balance',
    nameEn: '180A SCS Analytical Balance',
    nameFr: 'Balance analytique 180A SCS',
    ref: '180A-SCS',
    specs: ['180 g capacity', '0.0001 g readout', 'Draft shield'],
    specsFr: ['Portée 180 g', 'Lecture 0,0001 g', 'Pare-souffle'],
    description: 'High-precision analytical balance with SCS anti-static technology.',
    descriptionFr: 'Balance analytique haute précision avec technologie anti-statique SCS.',
    pdf: null,
    image: '/assets/images/products/precisa/360_Analytical_Balance-1.png'
  },
  {
    id: 'precisa-bj610c',
    brand: 'Precisa',
    brandSlug: 'precisa',
    category: 'laboratory',
    subcategory: 'balances',
    name: 'BJ 610C Precision Balance',
    nameEn: 'BJ 610C Precision Balance',
    nameFr: 'Balance de précision BJ 610C',
    ref: 'BJ-610C',
    specs: ['610 g capacity', '0.01 g readout', 'RS232'],
    specsFr: ['Portée 610 g', 'Lecture 0,01 g', 'RS232'],
    description: 'Reliable precision balance for routine weighing in laboratory environments.',
    descriptionFr: 'Balance de précision fiable pour la pesée de routine en laboratoire.',
    pdf: null,
    image: '/assets/images/products/precisa/520_analytical_balance.png'
  },

  /* ────────────────────────────────
     LABORATORY — TESTO
     ──────────────────────────────── */
  {
    id: 'testo-435-4',
    brand: 'Testo',
    brandSlug: 'testo',
    category: 'laboratory',
    subcategory: 'meters',
    name: '435-4 Air Quality Meter',
    nameEn: '435-4 Air Quality Meter',
    nameFr: 'Appareil qualité d\'air 435-4',
    ref: 'TESTO-435-4',
    specs: ['CO₂', 'Temp & Humidity', 'IAQ index'],
    specsFr: ['CO₂', 'Temp & Humidité', 'Indice QAI'],
    description: 'Multifunction meter for indoor air quality: CO₂, temperature, humidity, air velocity.',
    descriptionFr: 'Appareil multifonction pour la qualité de l\'air intérieur : CO₂, température, humidité, vitesse d\'air.',
    pdf: null,
    image: '/assets/images/products/testo/testo-435-4-instrument-multifunction-002813.webp'
  },
  {
    id: 'testo-176-t4',
    brand: 'Testo',
    brandSlug: 'testo',
    category: 'laboratory',
    subcategory: 'loggers',
    name: '176 T4 Temperature Logger',
    nameEn: '176 T4 Temperature Logger',
    nameFr: 'Enregistreur de température 176 T4',
    ref: 'TESTO-176-T4',
    specs: ['4 channels', '2M readings', 'USB'],
    specsFr: ['4 canaux', '2M valeurs', 'USB'],
    description: '4-channel temperature data logger with 2 million reading memory and USB connectivity.',
    descriptionFr: 'Enregistreur de température 4 canaux avec mémoire 2 millions de valeurs et connexion USB.',
    pdf: null,
    image: '/assets/images/products/testo/testo-176t4-front-0572-1764-int-2000x1500.webp'
  },
  {
    id: 'testo-340',
    brand: 'Testo',
    brandSlug: 'testo',
    category: 'laboratory',
    subcategory: 'meters',
    name: '340 Flue Gas Analyzer',
    nameEn: '340 Flue Gas Analyzer',
    nameFr: 'Analyseur de gaz de combustion 340',
    ref: 'TESTO-340',
    specs: ['O₂, CO, NOx', 'Industrial grade', 'Wireless'],
    specsFr: ['O₂, CO, NOx', 'Grade industriel', 'Sans fil'],
    description: 'Industrial-grade flue gas analyzer for combustion optimization and emissions monitoring.',
    descriptionFr: 'Analyseur industriel de gaz de combustion pour l\'optimisation de la combustion et la surveillance des émissions.',
    pdf: null,
    image: '/assets/images/products/testo/testo-340-instrument-emission-000072.webp'
  },
  {
    id: 'testo-6651',
    brand: 'Testo',
    brandSlug: 'testo',
    category: 'laboratory',
    subcategory: 'meters',
    name: '6651 Humidity Transmitter',
    nameEn: '6651 Humidity Transmitter',
    nameFr: 'Transmetteur d\'humidité 6651',
    ref: 'TESTO-6651',
    specs: ['0–100% RH', '±1% RH accuracy', 'Probe exchange'],
    specsFr: ['0–100% HR', '±1% HR précision', 'Échange de sonde'],
    description: 'High-accuracy humidity and temperature transmitter for critical cleanroom and storage monitoring.',
    descriptionFr: 'Transmetteur haute précision humidité/température pour salles propres et surveillance de stockage critique.',
    pdf: null,
    image: '/assets/images/products/testo/testo-6651-instrument-stationary-measurement-001539.webp'
  },
  {
    id: 'testo-saveris-2',
    brand: 'Testo',
    brandSlug: 'testo',
    category: 'laboratory',
    subcategory: 'loggers',
    name: 'Saveris 2 WiFi Logger',
    nameEn: 'Saveris 2 WiFi Logger',
    nameFr: 'Enregistreur WiFi Saveris 2',
    ref: 'TESTO-SAVERIS2',
    specs: ['WiFi connected', 'Cloud dashboard', 'GxP / HACCP'],
    specsFr: ['Connecté WiFi', 'Tableau de bord cloud', 'GxP / HACCP'],
    description: 'Cloud-connected data logger for temperature and humidity with alarm notification and GxP compliance.',
    descriptionFr: 'Enregistreur connecté au cloud pour température et humidité avec notification d\'alarme et conformité GxP.',
    pdf: null,
    image: '/assets/images/products/testo/testo-saveris-2-t1-instrument-stationary-measurement-005000.webp'
  },

  /* ────────────────────────────────
     LABORATORY — SARTORIUS
     ──────────────────────────────── */
  {
    id: 'sartorius-quintix-224',
    brand: 'Sartorius',
    brandSlug: 'sartorius',
    category: 'laboratory',
    subcategory: 'balances',
    name: 'Quintix 224-1S',
    nameEn: 'Quintix 224-1S Analytical Balance',
    nameFr: 'Balance analytique Quintix 224-1S',
    ref: 'QUINTIX-224-1S',
    specs: ['220 g capacity', '0.1 mg readout', 'isoCAL'],
    specsFr: ['Portée 220 g', 'Lecture 0,1 mg', 'isoCAL'],
    description: 'Semi-micro analytical balance with automatic internal calibration (isoCAL).',
    descriptionFr: 'Balance analytique semi-micro avec calibrage interne automatique (isoCAL).',
    pdf: null,
    image: '/assets/images/products/sartorius/sarftorius-quintix-draftshield__73371.1682096570.1280.1280.jpg'
  },
  {
    id: 'sartorius-secura-224',
    brand: 'Sartorius',
    brandSlug: 'sartorius',
    category: 'laboratory',
    subcategory: 'balances',
    name: 'Secura 224-1S',
    nameEn: 'Secura 224-1S GxP Balance',
    nameFr: 'Balance GxP Secura 224-1S',
    ref: 'SECURA-224-1S',
    specs: ['220 g capacity', '0.1 mg readout', 'GxP compliant'],
    specsFr: ['Portée 220 g', 'Lecture 0,1 mg', 'Conforme GxP'],
    description: 'GxP-compliant analytical balance with complete audit trail for regulated environments.',
    descriptionFr: 'Balance analytique conforme GxP avec piste d\'audit complète pour environnements réglementés.',
    pdf: null,
    image: '/assets/images/products/sartorius/sartorius-secura-analytical-balance__71746.1682096722.1280.1280.jpg'
  },

  /* ────────────────────────────────
     LABORATORY — EPPENDORF
     ──────────────────────────────── */
  {
    id: 'eppendorf-5425r',
    brand: 'Eppendorf',
    brandSlug: 'eppendorf',
    category: 'laboratory',
    subcategory: 'centrifuges',
    name: '5425R Refrigerated Centrifuge',
    nameEn: '5425R Refrigerated Centrifuge',
    nameFr: 'Centrifugeuse réfrigérée 5425R',
    ref: 'EPPEN-5425R',
    specs: ['15,000 rpm', '−9 to +40°C', '30 programs'],
    specsFr: ['15 000 tr/min', '−9 à +40°C', '30 programmes'],
    description: 'High-speed refrigerated microcentrifuge with 30 programmable methods.',
    descriptionFr: 'Microcentrifugeuse réfrigérée haute vitesse avec 30 méthodes programmables.',
    pdf: null,
    image: '/assets/images/products/eppendorf/Eppendorf_Centrifugation_Centrifuge-5425%2BR_FA-24x2_open_product.avif'
  },
  {
    id: 'eppendorf-thermomixer-c',
    brand: 'Eppendorf',
    brandSlug: 'eppendorf',
    category: 'laboratory',
    subcategory: 'mixers',
    name: 'Thermomixer C',
    nameEn: 'Thermomixer C',
    nameFr: 'Thermomixer C',
    ref: 'THERMO-C',
    specs: ['15–100°C', '300–3,000 rpm', 'Interchangeable'],
    specsFr: ['15–100°C', '300–3 000 tr/min', 'Interchangeable'],
    description: 'Versatile thermoblock with interchangeable blocks for tubes, plates and strips.',
    descriptionFr: 'Thermoblock polyvalent avec blocs interchangeables pour tubes, plaques et bandelettes.',
    pdf: null,
    image: '/assets/images/products/eppendorf/Eppendorf_Sample-Preparation_ThermoMixer_C-ACT_SmartBlock-15mL_product.avif'
  },
  {
    id: 'eppendorf-research-plus',
    brand: 'Eppendorf',
    brandSlug: 'eppendorf',
    category: 'laboratory',
    subcategory: 'pipettes',
    name: 'Research Plus Pipette',
    nameEn: 'Research Plus 100–1000 µL',
    nameFr: 'Pipette Research Plus 100–1000 µL',
    ref: 'RES-PLUS-1000',
    specs: ['100–1,000 µL', 'Autoclavable', 'GLP/GMP'],
    specsFr: ['100–1 000 µL', 'Autoclavable', 'GLP/BPF'],
    description: 'Ergonomic single-channel pipette with advanced piston technology for maximum precision.',
    descriptionFr: 'Pipette monocanal ergonomique avec technologie de piston avancée pour une précision maximale.',
    pdf: null,
    image: '/assets/images/products/eppendorf/Eppendorf_Liquid-Handling_Pipette-Family-Research-plus_product.avif'
  },
  {
    id: 'eppendorf-mastercycler-x50',
    brand: 'Eppendorf',
    brandSlug: 'eppendorf',
    category: 'laboratory',
    subcategory: 'pcr',
    name: 'Mastercycler X50',
    nameEn: 'Mastercycler X50 Thermal Cycler',
    nameFr: 'Thermocycleur Mastercycler X50',
    ref: 'MASTER-X50',
    specs: ['96-well block', '±0.1°C uniformity', 'Gradient'],
    specsFr: ['Bloc 96 puits', '±0,1°C uniformité', 'Gradient'],
    description: 'High-performance PCR thermal cycler with gradient function and intuitive software.',
    descriptionFr: 'Thermocycleur PCR haute performance avec fonction gradient et logiciel intuitif.',
    pdf: null,
    image: '/assets/images/products/eppendorf/Eppendorf_PCR_Mastercycler-X50_product.avif'
  },
  {
    id: 'eppendorf-xplorer-8',
    brand: 'Eppendorf',
    brandSlug: 'eppendorf',
    category: 'laboratory',
    subcategory: 'pipettes',
    name: 'Xplorer 8-Channel Pipette',
    nameEn: 'Xplorer 8-Channel Electronic Pipette',
    nameFr: 'Pipette électronique 8 canaux Xplorer',
    ref: 'XPLORER-8CH',
    specs: ['30–300 µL', '8 channels', 'Electronic'],
    specsFr: ['30–300 µL', '8 canaux', 'Électronique'],
    description: 'Versatile 8-channel electronic pipette for high-throughput plate work and dispensing.',
    descriptionFr: 'Pipette électronique 8 canaux polyvalente pour les travaux sur plaques à haut débit.',
    pdf: null,
    image: '/assets/images/products/eppendorf/Eppendorf_Liquid-Handling_Xplorer-plus-Move-It_product.avif'
  },

  /* ────────────────────────────────
     LABORATORY — MERCK
     ──────────────────────────────── */
  {
    id: 'merck-milli-q-iq7000',
    brand: 'Merck',
    brandSlug: 'merck',
    category: 'laboratory',
    subcategory: 'water-purification',
    name: 'Milli-Q IQ 7000',
    nameEn: 'Milli-Q IQ 7000 Ultrapure Water',
    nameFr: 'Système eau ultrapure Milli-Q IQ 7000',
    ref: 'MILLIQ-IQ7000',
    specs: ['Type 1 water', '≥18.2 MΩ·cm', 'TOC <1 ppb'],
    specsFr: ['Eau Type 1', '≥18,2 MΩ·cm', 'COT <1 ppb'],
    description: 'Ultrapure Type 1 water system with real-time quality monitoring and cloud connectivity.',
    descriptionFr: 'Système d\'eau ultrapure Type 1 avec surveillance qualité en temps réel et connectivité cloud.',
    pdf: null,
    image: '/assets/images/products/merck/22197ab7-274d-499c-92f3-b966c39c723e.avif'
  },
  {
    id: 'merck-spectroquant-prove300',
    brand: 'Merck',
    brandSlug: 'merck',
    category: 'laboratory',
    subcategory: 'spectrophotometers',
    name: 'Spectroquant Prove 300',
    nameEn: 'Spectroquant Prove 300 UV-Vis',
    nameFr: 'Spectrophotomètre UV-Vis Spectroquant Prove 300',
    ref: 'SPECTR-PROVE300',
    specs: ['320–1100 nm', 'UV-Vis', '700+ methods'],
    specsFr: ['320–1100 nm', 'UV-Vis', '700+ méthodes'],
    description: 'Full-spectrum UV-Vis spectrophotometer with 700+ pre-loaded analysis methods.',
    descriptionFr: 'Spectrophotomètre UV-Vis spectre complet avec plus de 700 méthodes d\'analyse préchargées.',
    pdf: null,
    image: '/assets/images/products/merck/ff975ebb-7e75-4285-a3bd-792191a89b45.avif'
  },
  {
    id: 'merck-direct-q3',
    brand: 'Merck',
    brandSlug: 'merck',
    category: 'laboratory',
    subcategory: 'water-purification',
    name: 'Direct-Q 3 UV-R',
    nameEn: 'Direct-Q 3 UV-R Pure Water System',
    nameFr: 'Système eau pure Direct-Q 3 UV-R',
    ref: 'DIRECTQ-3UVR',
    specs: ['Type 2 water', 'UV lamp', 'Integrated pump'],
    specsFr: ['Eau Type 2', 'Lampe UV', 'Pompe intégrée'],
    description: 'Compact Type 2 pure water system from tap water with UV disinfection, ideal for routine work.',
    descriptionFr: 'Système compact d\'eau pure Type 2 à partir du robinet avec désinfection UV, idéal pour les travaux de routine.',
    pdf: null,
    image: '/assets/images/products/merck/a49ffff8-2e1f-48dd-b790-dcd186b98d4d.avif'
  },
  {
    id: 'merck-novablue-staining',
    brand: 'Merck',
    brandSlug: 'merck',
    category: 'laboratory',
    subcategory: 'reagents',
    name: 'Novablue Staining Kit',
    nameEn: 'Novablue Staining Kit',
    nameFr: 'Kit de coloration Novablue',
    ref: 'NOVA-BLUE-KIT',
    specs: ['Gel electrophoresis', 'Coomassie R-250', 'Ready-to-use'],
    specsFr: ['Électrophorèse sur gel', 'Coomassie R-250', 'Prêt à l\'emploi'],
    description: 'Ready-to-use Coomassie staining kit for SDS-PAGE protein gels with fast destaining.',
    descriptionFr: 'Kit de coloration Coomassie prêt à l\'emploi pour gels de protéines SDS-PAGE avec décoloration rapide.',
    pdf: null,
    image: '/assets/images/products/merck/e4e669e5-10e4-4783-87d5-720d3f4beff4.avif'
  },

  /* ────────────────────────────────
     CHEMISTRY — SRL INDIA
     ──────────────────────────────── */
  {
    id: 'srl-acetonitrile-hplc',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'solvents',
    name: 'Acetonitrile HPLC Grade',
    nameEn: 'Acetonitrile HPLC Grade',
    nameFr: 'Acétonitrile Grade CLHP',
    ref: 'SRL-ACN-HPLC',
    specs: ['≥99.9% purity', '2.5 L / 4 L', 'UV transparent'],
    specsFr: ['Pureté ≥99,9%', '2,5 L / 4 L', 'Transparent UV'],
    description: 'Ultra-pure acetonitrile for HPLC/UHPLC, LC-MS. Low UV absorbance.',
    descriptionFr: 'Acétonitrile ultra-pur pour CLHP/UHPLC, LC-MS. Faible absorbance UV.',
    pdf: null,
    image: '/assets/images/products/srl/solvents.svg'
  },
  {
    id: 'srl-methanol-hplc',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'solvents',
    name: 'Methanol HPLC Grade',
    nameEn: 'Methanol HPLC Grade',
    nameFr: 'Méthanol Grade CLHP',
    ref: 'SRL-MeOH-HPLC',
    specs: ['≥99.9% purity', '2.5 L / 4 L', 'UV transparent'],
    specsFr: ['Pureté ≥99,9%', '2,5 L / 4 L', 'Transparent UV'],
    description: 'High-purity methanol for HPLC, spectroscopy and analytical applications.',
    descriptionFr: 'Méthanol haute pureté pour CLHP, spectroscopie et applications analytiques.',
    pdf: null,
    image: '/assets/images/products/srl/solvents.svg'
  },
  {
    id: 'srl-hcl-37',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'acids',
    name: 'Hydrochloric Acid 37% AR',
    nameEn: 'Hydrochloric Acid 37% AR Grade',
    nameFr: 'Acide chlorhydrique 37% Grade AR',
    ref: 'SRL-HCl-37-AR',
    specs: ['37% HCl', '500 mL / 2.5 L', 'AR Grade'],
    specsFr: ['37% HCl', '500 mL / 2,5 L', 'Grade AR'],
    description: 'Analytical reagent grade hydrochloric acid for titration and sample preparation.',
    descriptionFr: 'Acide chlorhydrique grade réactif analytique pour titration et préparation d\'échantillons.',
    pdf: null,
    image: '/assets/images/products/srl/acids.svg'
  },
  {
    id: 'srl-h2so4-98',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'acids',
    name: 'Sulfuric Acid 98% AR',
    nameEn: 'Sulfuric Acid 98% AR Grade',
    nameFr: 'Acide sulfurique 98% Grade AR',
    ref: 'SRL-H2SO4-AR',
    specs: ['98% H₂SO₄', '500 mL / 2.5 L', 'AR Grade'],
    specsFr: ['98% H₂SO₄', '500 mL / 2,5 L', 'Grade AR'],
    description: 'High-purity analytical grade sulfuric acid for digestion and analytical chemistry.',
    descriptionFr: 'Acide sulfurique grade analytique haute pureté pour digestion et chimie analytique.',
    pdf: null,
    image: '/assets/images/products/srl/acids.svg'
  },
  {
    id: 'srl-naoh-ar',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'bases',
    name: 'Sodium Hydroxide AR',
    nameEn: 'Sodium Hydroxide (Pellets) AR Grade',
    nameFr: 'Hydroxyde de sodium (pastilles) Grade AR',
    ref: 'SRL-NaOH-AR',
    specs: ['≥97% NaOH', '500 g / 1 kg', 'Pellets'],
    specsFr: ['≥97% NaOH', '500 g / 1 kg', 'Pastilles'],
    description: 'Analytical grade sodium hydroxide pellets for titration, pH adjustment and synthesis.',
    descriptionFr: 'Pastilles d\'hydroxyde de sodium grade analytique pour titration, ajustement du pH et synthèse.',
    pdf: null,
    image: '/assets/images/products/srl/bases.svg'
  },
  {
    id: 'srl-buffer-ph4',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'buffers',
    name: 'pH Buffer 4.00',
    nameEn: 'pH Buffer Solution 4.00',
    nameFr: 'Solution tampon pH 4,00',
    ref: 'SRL-BUF-pH4',
    specs: ['pH 4.00 ±0.01', '500 mL', 'NIST traceable'],
    specsFr: ['pH 4,00 ±0,01', '500 mL', 'Traçable NIST'],
    description: 'NIST-traceable pH 4.00 buffer solution for pH meter calibration.',
    descriptionFr: 'Solution tampon pH 4,00 traçable NIST pour l\'étalonnage des pH-mètres.',
    pdf: null,
    image: '/assets/images/products/srl/buffers.svg'
  },
  {
    id: 'srl-buffer-ph7',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'buffers',
    name: 'pH Buffer 7.00',
    nameEn: 'pH Buffer Solution 7.00',
    nameFr: 'Solution tampon pH 7,00',
    ref: 'SRL-BUF-pH7',
    specs: ['pH 7.00 ±0.01', '500 mL', 'NIST traceable'],
    specsFr: ['pH 7,00 ±0,01', '500 mL', 'Traçable NIST'],
    description: 'NIST-traceable pH 7.00 neutral buffer solution for pH meter calibration.',
    descriptionFr: 'Solution tampon pH 7,00 neutre traçable NIST pour l\'étalonnage des pH-mètres.',
    pdf: null,
    image: '/assets/images/products/srl/buffers.svg'
  },
  {
    id: 'srl-buffer-ph10',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'buffers',
    name: 'pH Buffer 10.00',
    nameEn: 'pH Buffer Solution 10.00',
    nameFr: 'Solution tampon pH 10,00',
    ref: 'SRL-BUF-pH10',
    specs: ['pH 10.00 ±0.01', '500 mL', 'NIST traceable'],
    specsFr: ['pH 10,00 ±0,01', '500 mL', 'Traçable NIST'],
    description: 'NIST-traceable pH 10.00 alkaline buffer solution for pH meter calibration.',
    descriptionFr: 'Solution tampon pH 10,00 alcalin traçable NIST pour l\'étalonnage des pH-mètres.',
    pdf: null,
    image: '/assets/images/products/srl/buffers.svg'
  },

  /* ── SRL: More Solvents ── */
  {
    id: 'srl-acetone-ar',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'solvents',
    name: 'Acetone AR Grade',
    nameEn: 'Acetone AR Grade',
    nameFr: 'Acétone Grade AR',
    ref: 'SRL-ACE-AR',
    specs: ['≥99.5% purity', '500 mL / 2.5 L', 'AR Grade'],
    specsFr: ['Pureté ≥99,5%', '500 mL / 2,5 L', 'Grade AR'],
    description: 'Analytical reagent grade acetone for extraction, degreasing and analytical chemistry.',
    descriptionFr: 'Acétone grade réactif analytique pour l\'extraction, le dégraissage et la chimie analytique.',
    pdf: null,
    image: '/assets/images/products/srl/solvents.svg'
  },
  {
    id: 'srl-ethanol-95',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'solvents',
    name: 'Ethanol 95% AR Grade',
    nameEn: 'Ethanol 95% AR Grade',
    nameFr: 'Éthanol 95% Grade AR',
    ref: 'SRL-EtOH-95-AR',
    specs: ['95% v/v', '500 mL / 2.5 L', 'AR Grade'],
    specsFr: ['95% v/v', '500 mL / 2,5 L', 'Grade AR'],
    description: 'Analytical grade ethanol for extraction, precipitation and molecular biology applications.',
    descriptionFr: 'Éthanol grade analytique pour l\'extraction, la précipitation et les applications de biologie moléculaire.',
    pdf: null,
    image: '/assets/images/products/srl/solvents.svg'
  },
  {
    id: 'srl-ethyl-acetate-hplc',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'solvents',
    name: 'Ethyl Acetate HPLC Grade',
    nameEn: 'Ethyl Acetate HPLC Grade',
    nameFr: 'Acétate d\'éthyle Grade CLHP',
    ref: 'SRL-EtOAc-HPLC',
    specs: ['≥99.8% purity', '2.5 L / 4 L', 'UV transparent'],
    specsFr: ['Pureté ≥99,8%', '2,5 L / 4 L', 'Transparent UV'],
    description: 'HPLC-grade ethyl acetate for normal-phase chromatography and sample preparation.',
    descriptionFr: 'Acétate d\'éthyle grade CLHP pour la chromatographie en phase normale et la préparation d\'échantillons.',
    pdf: null,
    image: '/assets/images/products/srl/solvents.svg'
  },
  {
    id: 'srl-hexane-hplc',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'solvents',
    name: 'n-Hexane HPLC Grade',
    nameEn: 'n-Hexane HPLC Grade',
    nameFr: 'n-Hexane Grade CLHP',
    ref: 'SRL-HEX-HPLC',
    specs: ['≥97% n-hexane', '2.5 L / 4 L', 'UV transparent'],
    specsFr: ['≥97% n-hexane', '2,5 L / 4 L', 'Transparent UV'],
    description: 'HPLC-grade n-hexane for lipid extraction, normal-phase chromatography and pesticide analysis.',
    descriptionFr: 'n-Hexane grade CLHP pour l\'extraction des lipides, la chromatographie en phase normale et l\'analyse des pesticides.',
    pdf: null,
    image: '/assets/images/products/srl/solvents.svg'
  },
  {
    id: 'srl-dcm-ar',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'solvents',
    name: 'Dichloromethane AR Grade',
    nameEn: 'Dichloromethane (DCM) AR Grade',
    nameFr: 'Dichlorométhane (DCM) Grade AR',
    ref: 'SRL-DCM-AR',
    specs: ['≥99.5% DCM', '500 mL / 2.5 L', 'AR Grade'],
    specsFr: ['≥99,5% DCM', '500 mL / 2,5 L', 'Grade AR'],
    description: 'Analytical grade dichloromethane for extraction, synthesis and chromatography.',
    descriptionFr: 'Dichlorométhane grade analytique pour l\'extraction, la synthèse et la chromatographie.',
    pdf: null,
    image: '/assets/images/products/srl/solvents.svg'
  },
  {
    id: 'srl-thf-hplc',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'solvents',
    name: 'Tetrahydrofuran HPLC Grade',
    nameEn: 'Tetrahydrofuran (THF) HPLC Grade',
    nameFr: 'Tétrahydrofurane (THF) Grade CLHP',
    ref: 'SRL-THF-HPLC',
    specs: ['≥99.9% purity', '1 L / 2.5 L', 'Stabilizer-free'],
    specsFr: ['Pureté ≥99,9%', '1 L / 2,5 L', 'Sans stabilisant'],
    description: 'Stabilizer-free HPLC-grade THF for GPC/SEC analysis and polymer characterization.',
    descriptionFr: 'THF grade CLHP sans stabilisant pour l\'analyse GPC/SEC et la caractérisation des polymères.',
    pdf: null,
    image: '/assets/images/products/srl/solvents.svg'
  },
  {
    id: 'srl-chloroform-ar',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'solvents',
    name: 'Chloroform AR Grade',
    nameEn: 'Chloroform AR Grade',
    nameFr: 'Chloroforme Grade AR',
    ref: 'SRL-CHCl3-AR',
    specs: ['≥99.0% CHCl₃', '500 mL / 2.5 L', 'AR Grade'],
    specsFr: ['≥99,0% CHCl₃', '500 mL / 2,5 L', 'Grade AR'],
    description: 'Analytical grade chloroform for DNA/RNA extraction, NMR and spectroscopy.',
    descriptionFr: 'Chloroforme grade analytique pour l\'extraction ADN/ARN, la RMN et la spectroscopie.',
    pdf: null,
    image: '/assets/images/products/srl/solvents.svg'
  },

  /* ── SRL: More Acids ── */
  {
    id: 'srl-hno3-65',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'acids',
    name: 'Nitric Acid 65% AR',
    nameEn: 'Nitric Acid 65% AR Grade',
    nameFr: 'Acide nitrique 65% Grade AR',
    ref: 'SRL-HNO3-65-AR',
    specs: ['65% HNO₃', '500 mL / 2.5 L', 'AR Grade'],
    specsFr: ['65% HNO₃', '500 mL / 2,5 L', 'Grade AR'],
    description: 'Analytical grade nitric acid for digestion, trace metal analysis and surface treatment.',
    descriptionFr: 'Acide nitrique grade analytique pour la digestion, l\'analyse des métaux traces et le traitement de surface.',
    pdf: null,
    image: '/assets/images/products/srl/acids.svg'
  },
  {
    id: 'srl-acetic-acid-glacial',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'acids',
    name: 'Acetic Acid Glacial AR',
    nameEn: 'Acetic Acid Glacial AR Grade',
    nameFr: 'Acide acétique glacial Grade AR',
    ref: 'SRL-AcOH-AR',
    specs: ['≥99.5% CH₃COOH', '500 mL / 2.5 L', 'AR Grade'],
    specsFr: ['≥99,5% CH₃COOH', '500 mL / 2,5 L', 'Grade AR'],
    description: 'Glacial acetic acid for buffer preparation, protein precipitation and organic synthesis.',
    descriptionFr: 'Acide acétique glacial pour la préparation de tampons, la précipitation des protéines et la synthèse organique.',
    pdf: null,
    image: '/assets/images/products/srl/acids.svg'
  },
  {
    id: 'srl-h3po4-85',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'acids',
    name: 'Phosphoric Acid 85% AR',
    nameEn: 'Phosphoric Acid 85% AR Grade',
    nameFr: 'Acide phosphorique 85% Grade AR',
    ref: 'SRL-H3PO4-AR',
    specs: ['85% H₃PO₄', '500 mL / 2.5 L', 'AR Grade'],
    specsFr: ['85% H₃PO₄', '500 mL / 2,5 L', 'Grade AR'],
    description: 'Analytical grade phosphoric acid for buffer preparation and HPLC mobile phase adjustment.',
    descriptionFr: 'Acide phosphorique grade analytique pour la préparation de tampons et l\'ajustement de la phase mobile CLHP.',
    pdf: null,
    image: '/assets/images/products/srl/acids.svg'
  },

  /* ── SRL: More Bases ── */
  {
    id: 'srl-koh-ar',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'bases',
    name: 'Potassium Hydroxide AR',
    nameEn: 'Potassium Hydroxide (Pellets) AR Grade',
    nameFr: 'Hydroxyde de potassium (pastilles) Grade AR',
    ref: 'SRL-KOH-AR',
    specs: ['≥85% KOH', '500 g / 1 kg', 'Pellets'],
    specsFr: ['≥85% KOH', '500 g / 1 kg', 'Pastilles'],
    description: 'Potassium hydroxide pellets for titration, saponification and base chemistry.',
    descriptionFr: 'Pastilles d\'hydroxyde de potassium pour la titration, la saponification et la chimie des bases.',
    pdf: null,
    image: '/assets/images/products/srl/bases.svg'
  },
  {
    id: 'srl-nh3-25',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'bases',
    name: 'Ammonia Solution 25% AR',
    nameEn: 'Ammonia Solution 25% AR Grade',
    nameFr: 'Solution d\'ammoniaque 25% Grade AR',
    ref: 'SRL-NH3-25-AR',
    specs: ['25% NH₃', '500 mL / 2.5 L', 'AR Grade'],
    specsFr: ['25% NH₃', '500 mL / 2,5 L', 'Grade AR'],
    description: 'Concentrated ammonia solution for pH adjustment, complexometry and organic synthesis.',
    descriptionFr: 'Solution d\'ammoniaque concentrée pour l\'ajustement du pH, la complexométrie et la synthèse organique.',
    pdf: null,
    image: '/assets/images/products/srl/bases.svg'
  },
  {
    id: 'srl-na2co3-ar',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'bases',
    name: 'Sodium Carbonate AR',
    nameEn: 'Sodium Carbonate Anhydrous AR Grade',
    nameFr: 'Carbonate de sodium anhydre Grade AR',
    ref: 'SRL-Na2CO3-AR',
    specs: ['≥99.5% Na₂CO₃', '500 g / 1 kg', 'Anhydrous'],
    specsFr: ['≥99,5% Na₂CO₃', '500 g / 1 kg', 'Anhydre'],
    description: 'Anhydrous sodium carbonate for gravimetric analysis, buffers and primary standard preparation.',
    descriptionFr: 'Carbonate de sodium anhydre pour l\'analyse gravimétrique, les tampons et la préparation de standards primaires.',
    pdf: null,
    image: '/assets/images/products/srl/bases.svg'
  },

  /* ── SRL: Indicators & Stains ── */
  {
    id: 'srl-phenolphthalein',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'indicators',
    name: 'Phenolphthalein Indicator',
    nameEn: 'Phenolphthalein 1% Solution Indicator',
    nameFr: 'Indicateur phénolphtaléine solution 1%',
    ref: 'SRL-PHP-IND',
    specs: ['pH 8.2–10.0', '100 mL', 'Ready-to-use'],
    specsFr: ['pH 8,2–10,0', '100 mL', 'Prêt à l\'emploi'],
    description: 'Ready-to-use phenolphthalein solution for acid-base titration endpoint detection.',
    descriptionFr: 'Solution de phénolphtaléine prête à l\'emploi pour la détection du point d\'équivalence en titration acido-basique.',
    pdf: null,
    image: '/assets/images/products/srl/indicators.svg'
  },
  {
    id: 'srl-methylene-blue',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'stains',
    name: 'Methylene Blue',
    nameEn: 'Methylene Blue Stain (0.1% Solution)',
    nameFr: 'Bleu de méthylène (solution 0,1%)',
    ref: 'SRL-MB-01',
    specs: ['0.1% solution', '100 mL', 'Microscopy grade'],
    specsFr: ['Solution 0,1%', '100 mL', 'Grade microscopie'],
    description: 'Methylene blue solution for cell and bacteria staining in light microscopy.',
    descriptionFr: 'Solution de bleu de méthylène pour la coloration des cellules et bactéries en microscopie optique.',
    pdf: null,
    image: '/assets/images/products/srl/stains.svg'
  },
  {
    id: 'srl-eosin-y',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'stains',
    name: 'Eosin Y Solution',
    nameEn: 'Eosin Y 1% Aqueous Solution',
    nameFr: 'Solution aqueuse Éosine Y 1%',
    ref: 'SRL-EOY-1',
    specs: ['1% solution', '100 mL', 'H&E staining'],
    specsFr: ['Solution 1%', '100 mL', 'Coloration H&E'],
    description: 'Eosin Y solution for histology H&E staining and cytological preparations.',
    descriptionFr: 'Solution d\'Éosine Y pour la coloration H&E en histologie et les préparations cytologiques.',
    pdf: null,
    image: '/assets/images/products/srl/stains.svg'
  },

  /* ── SRL: Reagents & Standards ── */
  {
    id: 'srl-edta-disodium',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'reagents',
    name: 'EDTA Disodium Salt AR',
    nameEn: 'EDTA Disodium Salt Dihydrate AR Grade',
    nameFr: 'Sel disodique d\'EDTA dihydraté Grade AR',
    ref: 'SRL-EDTA-2Na',
    specs: ['≥99.0% purity', '100 g / 500 g', 'AR Grade'],
    specsFr: ['Pureté ≥99,0%', '100 g / 500 g', 'Grade AR'],
    description: 'EDTA disodium dihydrate for complexometric titration, chelation and buffer systems.',
    descriptionFr: 'EDTA disodium dihydraté pour la titration complexométrique, la chélation et les systèmes tampons.',
    pdf: null,
    image: '/assets/images/products/srl/reagents.svg'
  },
  {
    id: 'srl-kh2po4-ar',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'reagents',
    name: 'Potassium Phosphate Monobasic',
    nameEn: 'Potassium Phosphate Monobasic AR Grade',
    nameFr: 'Phosphate de potassium monobasique Grade AR',
    ref: 'SRL-KH2PO4-AR',
    specs: ['≥99.5% KH₂PO₄', '500 g / 1 kg', 'AR Grade'],
    specsFr: ['≥99,5% KH₂PO₄', '500 g / 1 kg', 'Grade AR'],
    description: 'KH₂PO₄ for phosphate buffer preparation, HPLC mobile phases and cell culture media.',
    descriptionFr: 'KH₂PO₄ pour la préparation de tampons phosphate, les phases mobiles CLHP et les milieux de culture.',
    pdf: null,
    image: '/assets/images/products/srl/reagents.svg'
  },
  {
    id: 'srl-glucose-ar',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'reagents',
    name: 'D-Glucose Anhydrous AR',
    nameEn: 'D-Glucose Anhydrous AR Grade',
    nameFr: 'D-Glucose anhydre Grade AR',
    ref: 'SRL-GLUC-AR',
    specs: ['≥99.5% D-Glucose', '500 g / 1 kg', 'AR Grade'],
    specsFr: ['≥99,5% D-Glucose', '500 g / 1 kg', 'Grade AR'],
    description: 'Anhydrous D-glucose for cell culture media, standard solutions and biochemical assays.',
    descriptionFr: 'D-Glucose anhydre pour les milieux de culture cellulaire, les solutions étalons et les dosages biochimiques.',
    pdf: null,
    image: '/assets/images/products/srl/reagents.svg'
  },
  {
    id: 'srl-nacl-ar',
    brand: 'SRL',
    brandSlug: 'srl',
    category: 'chemistry',
    subcategory: 'reagents',
    name: 'Sodium Chloride AR',
    nameEn: 'Sodium Chloride AR Grade',
    nameFr: 'Chlorure de sodium Grade AR',
    ref: 'SRL-NaCl-AR',
    specs: ['≥99.5% NaCl', '500 g / 1 kg', 'AR Grade'],
    specsFr: ['≥99,5% NaCl', '500 g / 1 kg', 'Grade AR'],
    description: 'High-purity NaCl for buffer preparation, osmolarity adjustment and primary standards.',
    descriptionFr: 'NaCl haute pureté pour la préparation de tampons, l\'ajustement de l\'osmolarité et les standards primaires.',
    pdf: null,
    image: '/assets/images/products/srl/reagents.svg'
  }
];

/* Brand color accents for image placeholders */
const BRAND_COLORS = {
  'memmert':   '#C9A55C',
  'brookfield': '#C9A55C',
  'precisa':   '#C9A55C',
  'testo':     '#C9A55C',
  'sartorius': '#C9A55C',
  'eppendorf': '#C9A55C',
  'merck':     '#C9A55C',
  'srl':       '#C9A55C'
};

/* Category labels bilingual */
const CATEGORY_LABELS = {
  laboratory: { en: 'Laboratory Equipment', fr: 'Équipements de Laboratoire' },
  chemistry:  { en: 'Chemical Products', fr: 'Produits Chimiques' }
};

/* Subcategory labels bilingual */
const SUBCATEGORY_LABELS = {
  'ovens':             { en: 'Ovens & Drying', fr: 'Étuves & Séchage' },
  'incubators':        { en: 'Incubators', fr: 'Incubateurs' },
  'water-baths':       { en: 'Water Baths', fr: 'Bains-marie' },
  'viscometers':       { en: 'Viscometers & Rheometers', fr: 'Viscosimètres & Rhéomètres' },
  'balances':          { en: 'Balances & Scales', fr: 'Balances & Pesées' },
  'meters':            { en: 'Meters & Analyzers', fr: 'Appareils de mesure' },
  'loggers':           { en: 'Data Loggers', fr: 'Enregistreurs' },
  'centrifuges':       { en: 'Centrifuges', fr: 'Centrifugeuses' },
  'mixers':            { en: 'Mixers & Thermoblock', fr: 'Mélangeurs & Thermoblock' },
  'pipettes':          { en: 'Pipettes', fr: 'Pipettes' },
  'water-purification':{ en: 'Water Purification', fr: 'Purification d\'eau' },
  'spectrophotometers':{ en: 'Spectrophotometers', fr: 'Spectrophotomètres' },
  'pcr':               { en: 'PCR & Thermal Cyclers', fr: 'PCR & Thermocycleurs' },
  'reagents':          { en: 'Reagents & Standards', fr: 'Réactifs & Standards' },
  'solvents':          { en: 'Solvents', fr: 'Solvants' },
  'acids':             { en: 'Acids', fr: 'Acides' },
  'bases':             { en: 'Bases', fr: 'Bases' },
  'buffers':           { en: 'Buffer Solutions', fr: 'Solutions Tampon' },
  'indicators':        { en: 'Indicators', fr: 'Indicateurs' },
  'stains':            { en: 'Stains & Dyes', fr: 'Colorants & Révélateurs' }
};
